from flask import Flask, render_template, request, redirect, url_for, flash, session, jsonify, abort, Response, stream_with_context
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import SQLAlchemyError, IntegrityError
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy import ForeignKey, String, Integer, Text, Boolean, JSON, DateTime
from forms import AddNoteForm, EditNoteForm, LoginForm, RegisterForm, VerificationForm
from flask_login import UserMixin, login_user, LoginManager, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from helpers import send_email_threaded, create_code, build_ai_instructions, ask_mistral, ask_gemini, get_welcome_message, md_to_html, is_ai_error
from typing import Dict,Any
from datetime import datetime, timezone, timedelta
import json
import logging
from apscheduler.schedulers.background import BackgroundScheduler

class Base(DeclarativeBase):
    pass

app=Flask(__name__)
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0 # Ensure styling updates properly
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///notes.db"
app.config['SECRET_KEY'] = 'secretkey'
VERIFICATION_TTL_SECONDS = 10 * 60
NOTE_ACTION_COOLDOWN_SECONDS = 5 * 60

# ── Logging Configuration ──────────────────────────────────────────────
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
# Set Flask's built-in logger to DEBUG so all app.logger calls show up
app.logger.setLevel(logging.DEBUG)
app.logger.info("Flask application initialized — logging is active.")

db = SQLAlchemy(app, model_class=Base)

scheduler = BackgroundScheduler()

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'
login_manager.login_message = 'Please log in to access this page.'
login_manager.login_message_category = 'error'

class Note(db.Model):
    __tablename__ = 'notes'
    id: Mapped[int] = mapped_column(Integer, primary_key = True)
    title: Mapped[str] = mapped_column(String(100), nullable=False)
    html_content: Mapped[str] = mapped_column(Text, nullable=True, default=None)
    md_content: Mapped[str] = mapped_column(Text, nullable=True, default=None)    
    in_bin: Mapped[bool] = mapped_column(Boolean, nullable=False)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False)
    meta_data: Mapped[Dict[str,Any]] = mapped_column(JSON)
    last_opened : Mapped[datetime] = mapped_column(DateTime,default = lambda: datetime.now(timezone.utc), onupdate = lambda: datetime.now(timezone.utc))

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    password: Mapped[str] = mapped_column(String(1000), nullable=False)
    name: Mapped[str] = mapped_column(String(250), nullable=False)
    notes = relationship("Note", backref="author", lazy=True)

class Flashcard(db.Model):
    __tablename__ = 'flashcards'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    card_data: Mapped[Dict[str,Any]] = mapped_column(JSON)
    is_saved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False)

class Quiz(db.Model):
    __tablename__ = 'quizzes'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    quiz_data: Mapped[Dict[str,Any]] = mapped_column(JSON)
    is_saved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False)

def get_meta_data(content):
    metadata = build_ai_instructions(content,username='',metadata=True)
    return metadata

def normalize_metadata(metadata, note_id=None):
    """Create note metadata and fill in missing or invalid fields if any. 
    Makes metadata error tagged if any errors"""
    if isinstance(metadata, dict):
        normalized = dict(metadata)
    else:
        normalized = {
            'tags': ['error'],
            'summary': 'Metadata could not be generated for this note.',
            'is_invalid': True,
        }
    tags = normalized.get('tags')
    if not isinstance(tags, list):
        normalized['tags'] = []
    if not isinstance(normalized.get('summary'), str):
        normalized['summary'] = ''
    if note_id is not None:
        normalized['id'] = note_id
    return normalized

def metadata_needs_ai(metadata):
    """Checks if metadata needs to be generated by ai"""
    if not isinstance(metadata, dict):
        return True
    tags = metadata.get('tags', [])
    return metadata.get('is_invalid') is True or 'error' in tags

def metadata_for_search(note):
    """Checks if metadata can be used for note search"""
    metadata = note.meta_data
    if not isinstance(metadata, dict):
        return None
    tags = metadata.get('tags', [])
    if not isinstance(tags, list):
        tags = []
    if 'error' in tags or 'is_invalid' in tags or metadata.get('is_invalid') is True:
        return None
    return normalize_metadata(metadata, note.id)

def backfill_metadata_ids():
    """Sets metadata['id'] if not already set."""
    notes = db.session.scalars(db.select(Note)).all()
    changed = False
    for note in notes:
        if isinstance(note.meta_data, dict) and note.meta_data.get('id') != note.id:
            note.meta_data = normalize_metadata(note.meta_data, note.id)
            changed = True
    if changed:
        db.session.commit()
        app.logger.info("Backfilled metadata IDs for notes with missing or mismatched IDs.")

def generate_meta_data():
    """Generates meta data for notes with error notes or missing ids"""
    try:
        with app.app_context():
            notes = db.session.scalars(db.select(Note).order_by(Note.id.desc())).all()
            for note in notes:
                if isinstance(note.meta_data, dict) and note.meta_data.get('id') != note.id:
                    note.meta_data = normalize_metadata(note.meta_data, note.id)
            db.session.commit()
            # Select the first note which needs proper metadata
            note = next((n for n in notes if metadata_needs_ai(n.meta_data)), None)
            if not note:
                return

            metadata = get_meta_data(note.md_content)
            if metadata == 'error':
                app.logger.warning("Metadata generation returned 'error' for note_id=%s. Skipping.", note.id)
                return
            note.meta_data = normalize_metadata(metadata, note.id)
            db.session.commit()
            app.logger.info("Successfully generated metadata for note_id=%s.", note.id)
    except Exception:
        app.logger.exception("Unhandled exception in generate_meta_data background job.")
        return

def _clear_pending_auth():
    session.pop('pending_register', None)
    session.pop('pending_login', None)
    session.pop('pending_auth_code', None)
    session.pop('pending_auth_expires_at', None)
    session.pop('pending_auth_email', None)


def _verification_is_valid(submitted_code):
    """Checks if email verification code is correct"""
    expected_code = session.get('pending_auth_code')
    expires_at = session.get('pending_auth_expires_at')
    if not expected_code or not expires_at:
        return False, "Your verification session expired. Please start again."
    if datetime.now(timezone.utc).timestamp() > expires_at:
        _clear_pending_auth()
        return False, "Your verification code expired. Please start again."
    if submitted_code != expected_code:
        return False, "That verification code is incorrect."
    return True, ""

def delete_flashcards():
    """Delete unsaved flashcards"""
    all_flashcards = db.session.scalars(db.select(Flashcard).where(Flashcard.is_saved == False)).all()
    if all_flashcards:
        for flashcards in all_flashcards:
            db.session.delete(flashcards)
            db.session.commit()
    return

# Add the background job of generating metadata
scheduler.add_job(
    generate_meta_data,
    "interval",
    minutes=10,
    max_instances=1,
    coalesce=True
)

# Add background job of deleting unsaved flashcards
scheduler.add_job(
    delete_flashcards,
    "interval",
    minutes=10,
    max_instances=1,
    coalesce=True
)

with app.app_context():
    db.create_all()
    app.logger.info("Database tables created / verified.")
    try:
        with db.engine.connect() as conn:
            conn.execute(db.text("ALTER TABLE flashcards ADD COLUMN user_id INTEGER REFERENCES users(id)"))
            conn.commit()
            app.logger.info("Added user_id column to flashcards table.")
    except Exception:
        app.logger.debug("user_id column already exists in flashcards table (migration skipped).")
    backfill_metadata_ids()
scheduler.start() # Start the background process
app.logger.info("Background scheduler started.")

@login_manager.user_loader
def load_user(user_id):
    try:
        return db.session.get(User, int(user_id))
    except (SQLAlchemyError, ValueError) as e:
        app.logger.error("Failed to load user_id=%s: %s", user_id, e)
        return None

@app.route('/')
def home():
    welcome_msg = None
    recent_notes = []
    if current_user.is_authenticated:
        welcome_msg = get_welcome_message(current_user.name)
        try: 
            result = db.session.execute(
                        db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id).order_by(Note.last_opened.desc())
                    ) 
            recent_notes = result.scalars().all()
        except Exception as e:
            app.logger.error("[home] Failed to fetch recent notes for user_id=%s: %s", current_user.id, e)
            recent_notes = []   
    return render_template('index.html', welcome_msg = welcome_msg, recent_notes = recent_notes[:5])

@app.route('/notes')
@login_required
def notes():
    try:
        result = db.session.execute(
            db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id)
        )
        notes = result.scalars().all()
    except SQLAlchemyError as e:
        app.logger.error("[notes] DB error fetching notes for user_id=%s: %s", current_user.id, e)
        flash("An error occurred while fetching your notes. Please retry.", "error")
        notes = []
    return render_template('notes.html', notes=notes)

@app.route('/add', methods=['GET','POST'])
@login_required
def add_note():
    form = AddNoteForm()
    if form.validate_on_submit():
        try:
            content = form.content.data
            metadata = get_meta_data(content)
            note = Note(title=form.title.data, md_content=content,html_content = request.form.get('html_content') ,in_bin=False, user_id=current_user.id,meta_data=normalize_metadata(metadata))
            db.session.add(note)
            db.session.flush()
            note.meta_data = normalize_metadata(metadata, note.id)
            db.session.commit()
            flash('Note created successfully', 'success')
            return redirect(url_for('notes'))
        except SQLAlchemyError as e:
            db.session.rollback()
            app.logger.error("[add_note] DB error creating note for user_id=%s: %s", current_user.id, e)
            flash("Failed to create note due to a database error. Try again.", "error")
    return render_template('add_note.html', form=form)

@app.route('/edit/<int:note_id>', methods=['GET','POST'])
@login_required
def edit_note(note_id):
    try:
        note = db.session.get(Note, note_id)
        if not note or note.user_id != current_user.id:
            app.logger.warning("[edit_note] Note not found or unauthorized — note_id=%s, user_id=%s", note_id, current_user.id)
            flash("Note not found.", "error")
            return redirect(url_for('notes'))
    except SQLAlchemyError as e:
        app.logger.error("[edit_note] DB error fetching note_id=%s for user_id=%s: %s", note_id, current_user.id, e)
        flash("Error pulling note transaction records.", "error")
        return redirect(url_for('notes'))

    form = EditNoteForm()
    if request.method == 'GET':
        form.content.data = note.md_content
        
    if form.validate_on_submit():
        try:
            if form.content.data != note.md_content: # Check if user editted note content
                metadata = get_meta_data(form.content.data)
                note.meta_data = normalize_metadata(metadata, note.id)
            note.md_content = form.content.data
            note.html_content = request.form.get('html_content')
            db.session.commit()
            flash("Changes saved successfully!", "success")
            return redirect(url_for('notes'))
        except SQLAlchemyError as e:
            db.session.rollback()
            app.logger.error("[edit_note] DB error updating note_id=%s for user_id=%s: %s", note_id, current_user.id, e)
            flash("Could not update changes. Please check parameters.", "error")
            
    return render_template('edit_note.html', note=note, form=form)

@app.route('/move_to_bin/<int:note_id>',methods=['POST'])
@login_required
def move_to_bin(note_id):
    try:
        note = db.session.get(Note, note_id)
        if note and note.user_id == current_user.id:
            note.in_bin = True
            db.session.commit()
            return jsonify(['Note moved to bin','success'])
        else:
            app.logger.warning("[move_to_bin] Note not found or unauthorized — note_id=%s, user_id=%s", note_id, current_user.id)
            return jsonify(["Note not found", "error"])
    except SQLAlchemyError as e:
        db.session.rollback()
        app.logger.error("[move_to_bin] DB error for note_id=%s, user_id=%s: %s", note_id, current_user.id, e)
        return jsonify(["Could not move note to bin", "error"])

@app.route('/note-bin')
@login_required
def note_bin():
    try:
        result = db.session.execute(db.select(Note).where(Note.in_bin == True).where(Note.user_id == current_user.id))
        notes = result.scalars().all()
    except SQLAlchemyError as e:
        app.logger.error("[note_bin] DB error fetching binned notes for user_id=%s: %s", current_user.id, e)
        flash("Error checking database trash allocations.", "error")
        notes = []
    return render_template('bin.html', notes=notes)

@app.route('/delete/<int:note_id>',methods=['POST'])
@login_required
def delete(note_id):
    try:
        note = db.session.get(Note, note_id)
        if note and note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            return jsonify(["Note permanently deleted", "success"])
        else:
            app.logger.warning("[delete] Note not found or unauthorized — note_id=%s, user_id=%s", note_id, current_user.id)
            return jsonify(["Note not found", "error"])
    except SQLAlchemyError as e:
        db.session.rollback()
        app.logger.error("[delete] DB error permanently deleting note_id=%s for user_id=%s: %s", note_id, current_user.id, e)
        return jsonify(["Failed to delete note", "error"])

@app.route('/restore/<int:note_id>',methods=['POST'])
@login_required
def restore(note_id):
    try:
        note = db.session.get(Note, note_id)
        if note and note.user_id == current_user.id:
            note.in_bin = False
            db.session.commit()
            return jsonify(['Note restored', 'success'])
        else:
            app.logger.warning("[restore] Note not found or unauthorized — note_id=%s, user_id=%s", note_id, current_user.id)
            return jsonify(["Note not found.", "error"])
    except SQLAlchemyError as e:
        db.session.rollback()
        app.logger.error("[restore] DB error restoring note_id=%s for user_id=%s: %s", note_id, current_user.id, e)
        return jsonify(["Failed to restore note.", "error"])

@app.route('/register', methods=['GET','POST'])
def register():
    if session.get('pending_register'):
        form = VerificationForm()
        if form.validate_on_submit():
            is_valid, message = _verification_is_valid(form.code.data.strip())
            if not is_valid:
                flash(message, "error")
                return render_template(
                    'register.html',
                    form=form,
                    show_code=True,
                    verification_email=session.get('pending_auth_email'),
                )
            pending_register = session.get('pending_register')
            try:
                user = User(
                    email=pending_register['email'],
                    name=pending_register['name'],
                    password=pending_register['password'],
                )
                db.session.add(user)
                db.session.commit()
                login_user(user)
                _clear_pending_auth()
                flash(f'Created new account for {user.name}', 'success')
                return redirect(url_for('notes'))
            except IntegrityError as e:
                db.session.rollback()
                _clear_pending_auth()
                app.logger.warning("[register] Duplicate email on verification commit: %s", e)
                flash("That email address is already registered.", "error")
            except SQLAlchemyError as e:
                db.session.rollback()
                app.logger.error("[register] DB error creating user account: %s", e)
                flash("An unexpected error occurred. Please try again.", "error")
        return render_template(
            'register.html',
            form=form,
            show_code=True,
            verification_email=session.get('pending_auth_email'),
        )

    form = RegisterForm()
    if form.validate_on_submit():
        try:
            _clear_pending_auth()
            existing_user = db.session.execute(db.select(User).where(User.email == form.email.data)).scalar()
            if existing_user:
                flash("That email address is already registered.", "error")
                return render_template('register.html', form=form, show_code=False)

            verification_code = create_code()
            # Store the pending register details
            session['pending_register'] = {
                'name': form.name.data,
                'email': form.email.data,
                'password': generate_password_hash(form.password.data, method='pbkdf2:sha256', salt_length=16),
            }
            session['pending_auth_code'] = verification_code
            session['pending_auth_expires_at'] = datetime.now(timezone.utc).timestamp() + VERIFICATION_TTL_SECONDS
            session['pending_auth_email'] = form.email.data
            if not send_email_threaded(
                form.email.data,
                "Your verification code",
                f"Type this 6 digit code to finish your account setup: {verification_code}",
            ):
                raise RuntimeError("Failed to send verification email.")
            
            flash(f'Type the 6 digit code sent to {form.email.data}.', 'success')
            return render_template(
                'register.html',
                form=VerificationForm(),
                show_code=True,
                verification_email=form.email.data,
            )
        except IntegrityError as e:
            db.session.rollback()
            app.logger.warning("[register] Duplicate email during registration: %s", e)
            flash("That email address is already registered.", "error")
        except SQLAlchemyError as e:
            db.session.rollback()
            app.logger.error("[register] DB error during registration flow: %s", e)
            flash("An unexpected error occurred. Please try again.", "error")
        except Exception as e:
            db.session.rollback()
            app.logger.exception("[register] Unexpected error during registration (email send or other): %s", e)
            flash("Failed to send email. Try to register again.","error")
    return render_template('register.html', form=form)

@app.route('/login', methods=['GET','POST'])
def login():
    if session.get('pending_login'):
        form = VerificationForm()
        if form.validate_on_submit():
            is_valid, message = _verification_is_valid(form.code.data.strip())
            if not is_valid:
                flash(message, "error")
                return render_template(
                    'login.html',
                    form=form,
                    show_code=True,
                    verification_email=session.get('pending_auth_email'),
                )
            pending_login = session.get('pending_login')
            try:
                user = db.session.get(User, pending_login['user_id'])
                if not user:
                    _clear_pending_auth()
                    flash("Your account could not be found. Please login again.", "error")
                    return redirect(url_for('login'))
                login_user(user)
                _clear_pending_auth()
                flash(f'Welcome back {user.name}', 'success')
                return redirect(url_for('notes'))
            except SQLAlchemyError as e:
                app.logger.error("[login] DB error during login verification for user_id=%s: %s", pending_login.get('user_id'), e)
                flash("Internal database communication mismatch.", "error")
        return render_template(
            'login.html',
            form=form,
            show_code=True,
            verification_email=session.get('pending_auth_email'),
        )

    form = LoginForm()
    if form.validate_on_submit():
        try:
            _clear_pending_auth()
            user = db.session.execute(db.select(User).where(User.email == form.email.data)).scalar()
            if user and check_password_hash(user.password, form.password.data):
                verification_code = create_code()
                session['pending_login'] = {'user_id': user.id}
                session['pending_auth_code'] = verification_code
                session['pending_auth_expires_at'] = datetime.now(timezone.utc).timestamp() + VERIFICATION_TTL_SECONDS
                session['pending_auth_email'] = user.email
                send_email_threaded(
                    user.email,
                    "Your verification code",
                    f"Type this 6 digit code to finish your login: {verification_code}",
                )
                flash(f'Type the 6 digit code sent to {user.email}.', 'success')
                return render_template(
                    'login.html',
                    form=VerificationForm(),
                    show_code=True,
                    verification_email=user.email,
                )
            else:
                flash('Incorrect login credentials.', 'error')
        except SQLAlchemyError as e:
            app.logger.error("[login] DB error during login for email=%s: %s", form.email.data, e)
            flash("Internal database communication mismatch.", "error")
    return render_template('login.html', form=form, show_code=False)
    
@app.route('/logout',methods=['POST'])
@login_required
def logout():
    try:
        logout_user()
        app.logger.info("[logout] User logged out successfully.")
        return jsonify(['Logged out successfully', 'success'])
    except Exception as e:
        app.logger.error("[logout] Logout failed: %s", e)
        return jsonify(['Logout failed','error'])

@app.route('/search/<query>')
@login_required
def search(query):
    query = query.strip()
    if not query:
        return {"results": []}    
    try:
        result = db.session.execute(
            db.select(Note).where(Note.user_id == current_user.id).where(Note.title.contains(query))
        )
        notes = result.scalars().all()
        results = [{"id": note.id, "title": note.title} for note in notes]
        return jsonify({"results": results})
    except SQLAlchemyError as e:
        app.logger.error("[search] DB error searching notes for user_id=%s, query='%s': %s", current_user.id, query, e)
        return jsonify({"results": []})

@app.route('/search-results/<query>')
@login_required
def search_results(query):
    query = query.strip()
    if not query:
        return render_template('search-results.html', query=query, notes=[])
    try:
        result = db.session.execute(
            db.select(Note).where(Note.user_id == current_user.id).where(Note.title.contains(query))
        )
        notes = result.scalars().all()
        return render_template('search-results.html', query=query, notes=notes)
    except SQLAlchemyError as e:
        app.logger.error("[search_results] DB error for user_id=%s, query='%s': %s", current_user.id, query, e)
        return render_template('search-results.html', query=query, notes=[])

@app.route('/ai-chat')
@login_required
def ai_chat():
    welcome_message = get_welcome_message(current_user.name)
    return render_template('ai-chat.html',welcome_message=welcome_message)

@app.route('/ai-response', methods=['POST'])
@login_required
def ai_response():
    username = current_user.name
    data = request.get_json()
    message = data.get('contents')

    cooldown_until = session.get('note_action_cooldown_until')
    is_on_cooldown = cooldown_until and datetime.now(timezone.utc).timestamp() < cooldown_until

    all_instructions = build_ai_instructions(contents=message, username=username, chat_only=is_on_cooldown)
    all_results = []
    all_get_notes = ''
    note_action_html_content = ''
    flashcard_id = None
    quiz_id = None
    chat = None
    all_errors = []
    hit_rate_limit = False

    for instruction in all_instructions:
        action = instruction['action']
        ai_reply = instruction['content']

        if action == 'error':
            if isinstance(ai_reply, dict):
                app.logger.error("[ai_response] AI error (type=%s): %s", ai_reply.get('type'), ai_reply.get('msg'))
                all_errors.append(ai_reply.get('msg', 'An unexpected error occurred. Please try again later.'))
                if ai_reply.get('type') == 'rate_limit':
                    hit_rate_limit = True
            else:
                app.logger.error("[ai_response] AI returned unexpected non-dict error: %s", ai_reply)
                all_errors.append('NVLearn AI encountered an unexpected error. Please try again later.')

        elif action == 'chat':
            chat = ai_reply

        elif action == 'create_note':
            try:
                new_note = Note(
                    title=ai_reply['title'],
                    md_content=ai_reply['content'],
                    html_content=ai_reply['html_content'],
                    in_bin=False,
                    user_id=current_user.id,
                    meta_data=normalize_metadata(ai_reply.get('meta_data'))
                )
                db.session.add(new_note)
                db.session.flush()
                new_note.meta_data = normalize_metadata(new_note.meta_data, new_note.id)
                db.session.commit()
                all_results.append(f"Made new note '{ai_reply['title']}'")
            except Exception as e:
                db.session.rollback()
                app.logger.error("[ai_response/create_note] DB error saving AI-created note for user_id=%s: %s", current_user.id, e)
                all_errors.append('An error occurred while saving the new note to the database. Please try again.')

        elif action == 'get_note':
            metadata_list = []
            search_terms = str(ai_reply).lower().split()
            keywords = [word for word in search_terms if len(word)>3]
            notes = db.session.execute(
                db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id)
            ).scalars().all()
            for note in notes:
                metadata = metadata_for_search(note)
                if not metadata:
                    continue
                if not keywords:
                    metadata_list.append(metadata)
                    continue
                tags = metadata.get('tags', [])
                tags_text = " ".join(tags).lower()
                summary_text = metadata.get('summary','').lower()
                md_content = (note.md_content or '').lower()
                title = (note.title or '').lower()
                searchable_pool = f"{title} {tags_text} {summary_text} {md_content}"

                if any(keyword in searchable_pool for keyword in keywords):
                    metadata_list.append(metadata)

            note_ids = ask_mistral(f"Instruction: {ai_reply} Metadata list: {metadata_list}")
            note_content_list = ""

            if is_ai_error(note_ids):
                app.logger.error("[ai_response/get_note] Mistral error (type=%s): %s", note_ids.get('type'), note_ids.get('msg'))
                all_errors.append(note_ids.get('msg', f'An error occurred while fetching notes on "{ai_reply}". Please try again later.'))
                if note_ids.get('type') == 'rate_limit':
                    hit_rate_limit = True
            else:
                if note_ids.get('note_ids'):
                    for note_id in note_ids['note_ids']:
                        try:
                            note = db.session.get(Note, int(note_id))
                        except (TypeError, ValueError):
                            continue
                        if note and note.user_id == current_user.id:
                            note_content_list += (note.html_content or "") + '\n'
                else:
                    all_results.append(note_ids.get('msg', 'I could not find any relevant notes.'))
            all_get_notes += note_content_list

        elif action == 'note_action':
            metadata_list = []
            search_terms = str(ai_reply).lower().split()
            keywords = [word for word in search_terms if len(word)>3]
            notes = db.session.execute(
                db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id)
            ).scalars().all()
            for note in notes:
                metadata = metadata_for_search(note)
                if not metadata:
                    continue
                if not keywords:
                    metadata_list.append(metadata)
                    continue
                tags_text = " ".join(metadata.get('tags', [])).lower()
                summary_text = metadata.get('summary','').lower()
                md_content = (note.md_content or '').lower()
                title = (note.title or '').lower()
                searchable_pool = f"{title} {tags_text} {summary_text} {md_content}"

                if any(keyword in searchable_pool for keyword in keywords):
                    metadata_list.append(metadata)
            note_ids = ask_mistral(f"Instruction: {ai_reply} Metadata list: {metadata_list}")
            note_content_list = ''

            if is_ai_error(note_ids):
                app.logger.error("[ai_response/note_action] Mistral search error (type=%s): %s", note_ids.get('type'), note_ids.get('msg'))
                all_errors.append(note_ids.get('msg', 'An error occurred while searching for notes. Please try again later.'))
                if note_ids.get('type') == 'rate_limit':
                    hit_rate_limit = True
                continue
            else:
                if note_ids.get('note_ids'):
                    for note_id in note_ids['note_ids']:
                        try:
                            note = db.session.get(Note, int(note_id))
                        except (TypeError, ValueError):
                            continue
                        if note and note.user_id == current_user.id:
                            note_content_list += (note.md_content or "") + '\n'
                else:
                    all_results.append(note_ids.get('msg', 'I could not find any relevant notes.'))
                    continue

            gemini_result = ask_gemini(action='note_action', question=f"Instructions:{ai_reply} content:{note_content_list}")
            if is_ai_error(gemini_result):
                app.logger.error("[ai_response/note_action] Gemini error (type=%s): %s", gemini_result.get('type'), gemini_result.get('msg'))
                all_errors.append(gemini_result.get('msg', 'An error occurred while processing notes. Please try again later.'))
                if gemini_result.get('type') == 'rate_limit':
                    hit_rate_limit = True
            else:
                response_html, _ = gemini_result
                note_action_html_content += response_html + '\n'

        elif action == 'create_flashcards':
            metadata_list = []
            search_terms = str(ai_reply).lower().split()
            keywords = [word for word in search_terms if len(word) > 3]
            notes = db.session.execute(
                db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id)
            ).scalars().all()
            for note in notes:
                metadata = metadata_for_search(note)
                if not metadata:
                    continue
                if not keywords:
                    metadata_list.append(metadata)
                    continue
                tags_text = " ".join(metadata.get('tags', [])).lower()
                summary_text = metadata.get('summary','').lower()
                md_content = (note.md_content or '').lower()
                title = (note.title or '').lower()
                searchable_pool = f"{title} {tags_text} {summary_text} {md_content}"

                if any(keyword in searchable_pool for keyword in keywords):
                    metadata_list.append(metadata)
            note_ids = ask_mistral(f"Instruction: {ai_reply} Metadata list: {metadata_list}")
            note_content_list = ''

            if is_ai_error(note_ids):
                app.logger.warning("[ai_response/create_flashcards] Mistral note search failed (type=%s), falling back to topic. msg=%s", note_ids.get('type'), note_ids.get('msg'))
                note_content_list = f"Topic: {ai_reply}"
            else:
                if note_ids.get('note_ids'):
                    for note_id in note_ids['note_ids']:
                        try:
                            note = db.session.get(Note, int(note_id))
                        except (TypeError, ValueError):
                            continue
                        if note and note.user_id == current_user.id:
                            note_content_list += (note.md_content or "") + '\n'
                if not note_content_list:
                    note_content_list = f"Topic: {ai_reply}"

            gemini_result = ask_gemini(action='create_flashcards',question=note_content_list)
            if is_ai_error(gemini_result):
                app.logger.error("[ai_response/create_flashcards] Gemini flashcard generation failed (type=%s): %s", gemini_result.get('type'), gemini_result.get('msg'))
                all_errors.append(gemini_result.get('msg', 'An error occurred while processing notes. Flashcard could not be created. Please try again later.'))
                if gemini_result.get('type') == 'rate_limit':
                    hit_rate_limit = True
            else:
                flashcard = Flashcard(card_data = gemini_result, user_id = current_user.id)
                db.session.add(flashcard)
                db.session.commit()
                flashcard_id = flashcard.id
                all_results.append(f'Created flashcards on topic: {ai_reply}')

        elif action == 'create_quiz':
            metadata_list = []
            search_terms = str(ai_reply).lower().split()
            keywords = [word for word in search_terms if len(word) > 3]
            notes = db.session.execute(
                db.select(Note).where(Note.in_bin != True).where(Note.user_id == current_user.id)
            ).scalars().all()
            for note in notes:
                metadata = metadata_for_search(note)
                if not metadata:
                    continue
                if not keywords:
                    metadata_list.append(metadata)
                    continue
                tags_text = " ".join(metadata.get('tags', [])).lower()
                summary_text = metadata.get('summary','').lower()
                md_content = (note.md_content or '').lower()
                title = (note.title or '').lower()
                searchable_pool = f"{title} {tags_text} {summary_text} {md_content}"

                if any(keyword in searchable_pool for keyword in keywords):
                    metadata_list.append(metadata)
            note_ids = ask_mistral(f"Instruction: {ai_reply} Metadata list: {metadata_list}")
            note_content_list = ''

            if is_ai_error(note_ids):
                app.logger.warning("[ai_response/create_quiz] Mistral note search failed (type=%s), falling back to topic. msg=%s", note_ids.get('type'), note_ids.get('msg'))
                note_content_list = f"Topic: {ai_reply}"
            else:
                if note_ids.get('note_ids'):
                    for note_id in note_ids['note_ids']:
                        try:
                            note = db.session.get(Note, int(note_id))
                        except (TypeError, ValueError):
                            continue
                        if note and note.user_id == current_user.id:
                            note_content_list += (note.md_content or "") + '\n'
                if not note_content_list:
                    note_content_list = f"Topic: {ai_reply}"

            gemini_result = ask_gemini(action='create_quiz',question=note_content_list)
            if is_ai_error(gemini_result):
                app.logger.error("[ai_response/create_quiz] Gemini quiz generation failed (type=%s): %s", gemini_result.get('type'), gemini_result.get('msg'))
                all_errors.append(gemini_result.get('msg', 'An error occurred while processing notes. Quiz could not be created. Please try again later.'))
                if gemini_result.get('type') == 'rate_limit':
                    hit_rate_limit = True
            else:
                quiz_obj = Quiz(quiz_data=gemini_result, user_id=current_user.id)
                db.session.add(quiz_obj)
                db.session.commit()
                quiz_id = quiz_obj.id
                all_results.append(f'Created quiz on topic: {ai_reply}')

    if hit_rate_limit:
        session['note_action_cooldown_until'] = (datetime.now(timezone.utc) + timedelta(seconds=NOTE_ACTION_COOLDOWN_SECONDS)).timestamp()
        cooldown_msg = 'Note-related features are temporarily paused due to high demand. You can still chat normally — note features will be back in about 5 minutes.'
        if cooldown_msg not in all_errors:
            all_errors.append(cooldown_msg)

    final_result = {'results': all_results, 'errors': all_errors, 'chat': chat}
    errors = len(all_errors)
    results = len(all_results)

    if results == 0 and errors == 0 and not chat and note_action_html_content and all_get_notes == '':
        return jsonify({'note_action': note_action_html_content, 'flashcard_id': flashcard_id})

    if results <= 1 and errors <= 1 and not chat and not note_action_html_content:
        if results == 1 and errors == 0 and all_get_notes == '':
            return jsonify({'chat': all_results[0], 'flashcard_id': flashcard_id})
        elif results == 0 and errors == 1 and all_get_notes == '':
            return jsonify({'chat': all_errors[0], 'flashcard_id': flashcard_id})
        elif results == 0 and errors == 0 and all_get_notes != '':
            return jsonify({'chat': all_get_notes, 'flashcard_id': flashcard_id})
    if results == 0 and errors == 0 and chat:
        return jsonify({'chat': chat, 'flashcard_id': flashcard_id})

    final_summary = ask_gemini(question=final_result, action='summarize')
    if is_ai_error(final_summary):
        app.logger.error("[ai_response] Gemini summarize failed (type=%s): %s", final_summary.get('type'), final_summary.get('msg'))
        final_summary = chat or 'An error occurred while executing your task. Please try again.'
    output = {'chat': md_to_html(final_summary), 'notes': all_get_notes, 'note_action': note_action_html_content,'flashcard_id':flashcard_id}
    return jsonify(output)

@app.route('/read_note/<int:note_id>')
@login_required
def read_note(note_id):
    try:
        note = db.session.get(Note,note_id)
        note.last_opened = datetime.now(timezone.utc)
        db.session.commit()
        if not note or note.user_id != current_user.id:
            app.logger.warning("[read_note] Note not found or unauthorized — note_id=%s, user_id=%s", note_id, current_user.id)
            abort(404)
    except SQLAlchemyError as e:
        app.logger.error("[read_note] DB error reading note_id=%s for user_id=%s: %s", note_id, current_user.id, e)
        abort(404)
    return render_template('read_note.html',note=note)

@app.route('/flashcards/<int:flashcard_id>')
@login_required
def view_flashcards(flashcard_id):
    flashcard_obj = db.session.get(Flashcard, flashcard_id)
    if not flashcard_obj or flashcard_obj.user_id != current_user.id:
        app.logger.warning("[view_flashcards] Flashcard not found or unauthorized — flashcard_id=%s, user_id=%s", flashcard_id, current_user.id)
        abort(404)
    return render_template('view-flashcards.html', flashcards=flashcard_obj.card_data[1:],cards_id = flashcard_obj.id,is_saved=flashcard_obj.is_saved)

@app.route('/save-flashcards/<int:flashcard_id>',methods=['POST'])
@login_required
def save_flashcard(flashcard_id):
    flashcard_obj = db.session.get(Flashcard, flashcard_id)
    if flashcard_obj:
        flashcard_obj.is_saved = True
        db.session.commit()
        return jsonify({'status':'saved'})
    return jsonify({'status':'failed'})

@app.route('/delete-flashcards/<int:flashcard_id>',methods=['POST'])
@login_required
def delete_flashcard(flashcard_id):
    flashcard_obj = db.session.get(Flashcard, flashcard_id)
    if flashcard_obj and flashcard_obj.user_id == current_user.id:
        db.session.delete(flashcard_obj)
        db.session.commit()
        return jsonify(['Set deleted', 'success'])
    return jsonify(['Failed to delete', 'error'])

@app.route('/flashcards')
@login_required
def flashcards():
    all_flashcards = db.session.scalars(db.select(Flashcard).where(Flashcard.user_id == current_user.id).where(Flashcard.is_saved == True)).all()
    return render_template('flashcards.html', flashcards=all_flashcards)

@app.route('/quiz/<int:quiz_id>')
@login_required
def take_quiz(quiz_id):
    return render_template('take-quiz.html',quiz_id=quiz_id)

@app.route('/get-quiz-data/<int:quiz_id>',methods=['POST'])
@login_required
def get_quiz_data(quiz_id):
    quiz_obj = db.session.get(Quiz, quiz_id)
    if not quiz_obj or quiz_obj.user_id != current_user.id:
        app.logger.warning("[get_quiz_data] Quiz not found or unauthorized — quiz_id=%s, user_id=%s", quiz_id, current_user.id)
        return None
    return jsonify(quiz_obj.quiz_data)

@app.route('/about')
def about():
    return render_template('about.html')

@app.errorhandler(404)
def page_not_found(error):
    app.logger.warning("[404] Page not found: %s %s", request.method, request.url)
    return render_template('404.html'), 404

if __name__ == "__main__":
    app.run(debug=True, use_reloader=False)
